#############################
# Filebeat – JSON log to ES
#############################

filebeat.inputs:
  - type: filestream
    paths: [ "/app/Main/coordinator/logs/*.json" ]
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      service: coordinator
    processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: true
      

  - type: filestream
    paths: [ "/app/Consumers/consumer-postgresql/logs/*.json" ]
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      service: consumer-postgresql
    processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: true


  - type: filestream
    paths: [ "/app/Consumers/consumer-elasticsearch/logs/*.json" ]
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      service: consumer-elasticsearch
    processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: true




#############################
# Elasticsearch output
#############################

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "logs-%{[fields.service]}-%{+yyyy.MM.dd}"

#############################
# Template & Kibana setup
#############################

setup.template.name: "logs"
setup.template.pattern: "logs-*"
setup.ilm.enabled: false

setup.kibana:
  host: "kibana:5601"